# **PROGRAMMING WITH PYTHON - NUMPY**

In [1]:
import numpy as np

In [31]:
age = [15,30,40,53,35,50]
weight = [98,76,96,102,85,65]
height = [1.76,1.84,1.70,1.65,1.50,1.78]

In [33]:
[ (weight[i] / height[i] ** 2)  for i in range(6)]

[31.63739669421488,
 22.448015122873343,
 33.21799307958478,
 37.46556473829202,
 37.77777777777778,
 20.515086478979924]

In [34]:
list(map(lambda p,a: p/a**2,weight,height))

[31.63739669421488,
 22.448015122873343,
 33.21799307958478,
 37.46556473829202,
 37.77777777777778,
 20.515086478979924]

In [35]:
#weight / height ** 2

## **Arrays**

In [36]:
np_weight = np.array(weight)
np_height = np.array(height)

In [37]:
np_weight / np_height ** 2

array([31.63739669, 22.44801512, 33.21799308, 37.46556474, 37.77777778,
       20.51508648])

In [38]:
np.array([100,"number"]) # Is considered as a single type

array(['100', 'number'], dtype='<U21')

In [40]:
np.array([True,"number"])

array(['True', 'number'], dtype='<U6')

In [41]:
np.array([True,False])

array([ True, False])

In [42]:
np_weight < 70

array([False, False, False, False, False,  True])

In [43]:
np_weight[np_weight < 80]

array([76, 65])

### **Types of Arrays**

In [46]:
np_age = np.array([15,30,40,53,35,50])
np_weight = np.array([98,76,96,102,85,65])
np_height = np.array([1.76,1.84,1.70,1.65,1.50,1.78])

In [47]:
type(np_age),np_age.shape

(numpy.ndarray, (6,))

In [48]:
np_2d = np.array([
    [15,30,40,53,35,50],
    [98,76,96,102,85,65]
])

np_2d.shape

(2, 6)

In [49]:
np_2d[0][2],np_2d[0,2]

(40, 40)

In [50]:
np_2d[:,1:3]

array([[30, 40],
       [76, 96]])

In [51]:
np_2d[:,0],np_2d[:,1]

(array([15, 98]), array([30, 76]))

In [52]:
np.corrcoef(np_2d[0,:],np_2d[1,:])

array([[ 1.        , -0.17948175],
       [-0.17948175,  1.        ]])

In [53]:
np.std(np_weight)

13.140268896284683

In [54]:
np.mean(np_weight)

87.0

In [55]:
np.sum(np_weight)

522

In [56]:
np.sort(np_weight)

array([ 65,  76,  85,  96,  98, 102])

### **Data Generator**

In [57]:
r_height = np.round(np.random.normal(1.75,0.20,1000),2)
r_weight = np.round(np.random.normal(70.5,15,1000),2)

In [58]:
imc_np = np.column_stack((r_height,r_weight));imc_np

array([[ 2.2 , 67.17],
       [ 1.42, 45.06],
       [ 1.66, 60.25],
       ...,
       [ 1.55, 65.09],
       [ 1.74, 45.14],
       [ 1.93, 56.63]])

In [28]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [59]:
np.random.seed(45)
np_rand = np.random.rand(10)*10
np_unos = np.ones(10)

In [63]:
(np_rand, np_unos)

(array([9.89011513, 5.49544727, 2.81447302, 0.77289566, 4.44469496,
        4.7280797 , 0.48522001, 1.63324448, 1.15950711, 6.27391683]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]))

In [60]:
a = np.linspace(1994,2022,20)
b = np.random.normal(12,33,20)

In [65]:
(a, b)

(array([1994.        , 1995.47368421, 1996.94736842, 1998.42105263,
        1999.89473684, 2001.36842105, 2002.84210526, 2004.31578947,
        2005.78947368, 2007.26315789, 2008.73684211, 2010.21052632,
        2011.68421053, 2013.15789474, 2014.63157895, 2016.10526316,
        2017.57894737, 2019.05263158, 2020.52631579, 2022.        ]),
 array([ 25.00439767,  42.85848295,  11.48240465,  20.56666689,
        -36.61936996,  38.46357767, -45.77482876,  -4.33671374,
        -21.28382671,  12.83305813,   7.9902738 , -39.046815  ,
         -8.02915113, -33.99581819,  -8.71395132,  22.97686109,
        -38.86510578,  67.11989407,  -4.48501356,  34.21325583]))